package org.gangonem.model;

public enum MissingInfo {
	NONE, NO_STANDARDS_SET, NO_MALE_WALK_ON, NO_MALE_SOFT_RECRUIT, NO_MALE_HARD_RECRUIT, NO_FEMALE_WALK_ON,
	NO_FEMALE_SOFT_RECRUIT, NO_FEMALE_HARD_RECRUIT
}
